move functions to vcslib and sync git/svncheck; do not report exitcode unless update

diff --git a/files/gitcheck b/files/gitcheck
--- a/files/gitcheck
+++ b/files/gitcheck
@@ -2,8 +2,10 @@
 #####################
 # Managed by Puppet #
 #####################
-# svncheck
-# Usage: Check the status of SVN directory
+# gitcheck
+# https://github.com/ballestr/puppet-vcscheck
+# Usage: Check the status of VCS directory
+#
 # Author: saqib.haleem
 # Version: 1.0  18.8.2010
 # Update: 1.1 for /etc/svncheck
@@ -20,6 +22,8 @@
 # sergio.ballestrero 2015-01-24
 # Update: 2.0 version for Git
 # sergio.ballestrero 2017-05
+
+#[[ -t 0 || -n "$SSH_CONNECTION" ]] || set ## debug for cron
 
 # MYNAME=`readlink -f  "$0"` # -f fails on OsX
 MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #"#confusedmcedit
@@ -40,99 +44,19 @@ fi
 
 if [ "$1" = "-create" ]; then
    DO_CREATE=true
+   DO_EXITCODE=true
    shift
 fi
 
+TYPE="git"
 if [ $# -eq 0 ]; then
     shopt -s nullglob
-    CONFIGS="/etc/vcscheck/git_*.rc"
+    CONFIGS="/etc/vcscheck/${TYPE}_*.rc"
 else
     CONFIGS="$@"
 fi
 
-echo "$MYNAME"
-
-#source $MYDIR/vcslib.sh || exit 1
-source /usr/local/bin/vcslib.sh || exit 1
-
-function git_checkstatus() {
-    CHECK_LSTATUS=`git status --porcelain` 2>/dev/null
-    RL=${PIPESTATUS[0]}
-    CHECK_PSTATUS=`git status -v | egrep 'pull|push|ahead|detached'` 2>/dev/null
-    #CHECK_PSTATUS=`git status --porcelain -b | egrep 'pull|push|ahead|no branch'` 2>/dev/null ## not yet supperted in SLC6 git 1.7.1
-    RP=${PIPESTATUS[0]}
-    if [ "$VCSSRC" ]; then
-        CHECK_FSTATUS=`git fetch --dry-run 2>&1`
-        RF=${PIPESTATUS[0]}
-    else
-        CHECK_FSTATUS=""
-    fi
-    if [ "$CHECK_LSTATUS" == "" -a "$CHECK_PSTATUS" == "" -a "$CHECK_FSTATUS" == "" ]; then
-        echo "## $CONF: $VCS_DIR git status OK, fetch OK, pull OK" >> $USERMAIL
-    elif [[ "$CHECK_FSTATUS" =~ "Network connection" ]]; then
-        echo -e "## $CONF: network connection failure (s=$CHECK_STATUS):" >> $USERMAIL
-        echo $VCSSRC | sed -e 's/^/-- /' >> $USERMAIL
-        FAIL=1
-    else
-        echo -e "## $CONF: $VCS_DIR is not in sync or detached (r=$RL/$RP/$RF):" >> $USERMAIL
-        echo "--## git status -v :" >> $USERMAIL
-        git status -v 2>&1 | sed -e 's/^/-- /' >> $USERMAIL
-        if [ "$VCSSRC" ]; then
-            echo "--## git fetch dry-run :" >> $USERMAIL
-            git fetch --dry-run 2>&1 | sed -e 's/^/-- /' >> $USERMAIL
-        else
-            echo "--## local repo, no check on git fetch" >> $USERMAIL
-        fi
-        echo "--## git show -s :" >> $USERMAIL
-        git show -s 2>&1 | sed -e 's/^/-- /' >> $USERMAIL
-        FAIL=1
-    fi
-    if [ -f .gitmodules ]; then
-        CHECK_SSTATUS=`git submodule status --recursive| grep -v '^ '`
-        CHECK_SSTATUS+=`git submodule foreach --recursive "git status|grep detached||true" | grep -B1 detached`
-        RS=${PIPESTATUS[0]}
-        if [ "$CHECK_SSTATUS" == "" ]; then
-            echo "## $CONF: $VCS_DIR git submodule OK" >> $USERMAIL
-        else
-            echo "## $CONF: $VCS_DIR git submodule status --recursive :" >> $USERMAIL
-            git submodule status --recursive 2>&1 | sed -e 's/^/-- /' >> $USERMAIL
-            echo "## $CONF: $VCS_DIR git submodule foreach --recursive git status :" >> $USERMAIL
-            git submodule foreach --recursive "git status" 2>&1 | sed -e 's/^/-- /' >> $USERMAIL
-            FAIL=1
-        fi
-    fi
-}
-
-function git_update() {
-    local CHECK_LSTATUS=`git status --porcelain`
-    if [ "$CHECK_LSTATUS" == "" ]; then
-        local res=$(git fetch | grep -v "At revision")
-        if [ "$res" ]; then
-            echo "## $CONF: updated $VCS_DIR"
-            echo "$res"
-        fi
-    else
-        echo "## $CONF: unclean $VCS_DIR, skip update"
-        echo "$res"
-    fi
-}
-
-function git_create() {
-    echo "## $CONF: git clone --depth=1 $SOURCE $VCS_DIR"
-    git clone --depth=1 $SOURCE $VCS_DIR
-}
-
-function git_checkdir() {
-    if [ ! -e $VCS_DIR/.git ];  then
-        echo "## $CONF: $VCS_DIR is not a GIT working directory." >> $USERMAIL
-        return 1
-    fi
-    if [ -e $VCS_DIR/.git/svn ]; then
-        echo "## $CONF: $VCS_DIR is a GIT SVN working directory, not pure GIT." >> $USERMAIL
-        return 1
-    fi
-    return 0
-}
+source $MYDIR/vcslib.sh || source /usr/local/bin/vcslib.sh || exit 1
 
 FAILS=0
 for F in $CONFIGS; do
@@ -150,28 +74,27 @@ for F in $CONFIGS; do
             continue
         fi
 
-        if ! [ -e "$VCS_DIR" -a -e "$VCS_DIR/.git" ]; then
+        if ! vcs_isvcsdir; then
             if [ -n "$DO_CREATE" -a -n "$SOURCE" ]; then
                 ## if not empty, move aside
                 [ "ls -A $VCS_DIR" ] && mv $VCS_DIR $VCS_DIR.pre_vcscheck
-                git_create
+                vcs_create
             fi
         fi
 
-        # must cd to the path, else git status fails
+        # must cd to the path, else git status fails, svn status fails if it is a link
         if ! cd $VCS_DIR/ 2>/dev/null ;  then
             echo "## $CONF: $VCS_DIR is not accessible." >> $USERMAIL
             FAIL=1
             continue
         fi
 
-        if ! git_checkdir ; then
+        if ! vcs_checkdir; then
             FAIL=1
             continue
         fi
 
-        #VCSSRC=$(cd $VCS_DIR; git remote get-url origin) ## needs newer git
-        VCSSRC=$(cd $VCS_DIR; git remote -v | grep origin | grep fetch | sed -e "s/origin\s*//" -e "s/\s*(.*)//" ) #" confused mcedit
+        vcs_getsrc
 
         if [ -n "$SOURCE" ];  then
             if [ "$VCSSRC" != "$SOURCE" ]; then
@@ -185,20 +108,21 @@ for F in $CONFIGS; do
         [[ -t 0 || -p /dev/stdin || -n "$SSH_CONNECTION" ]] || sleep $[RANDOM%SPREAD]
         if [ "$AUTOUPDATE" == "true" -a -n "$DO_UPDATE" ]; then
             ## Check if running interactive, else send output to email
-            if [ -t 0 ]; then 
-                git_update
+            if [[ -t 0 || -n "$SSH_CONNECTION" ]]; then 
+                vcs_update
             else
-                git_update >> $UPDATEMAIL
+                vcs_update >> $UPDATEMAIL
             fi
         fi
-        git_checkstatus
+        vcs_checkstatus
     done
 
     ## Notifications
     if [ $FAIL -ne 0 ]; then
         vcsnotify $CONF $USERMAIL
-        if [ -t 0 ] ; then
+        if [[ -t 0 || -n "$SSH_CONNECTION" ]] ; then
             cat $USERMAIL
+            echo ""
         else
             if [ -z "$PUPSRV" ]; then 
                 ## send mail if no report server defined
@@ -223,8 +147,6 @@ fi
 
 rm $USERMAIL $UPDATEMAIL
 
-set
-
-## exit code, especially for puppet
-[ $FAILS -ne 0 ] && exit 1
+## exit code, especially for puppet -create
+[ -n "$DO_EXITCODE" -a $FAILS -ne 0 ] && exit 1
 exit 0
diff --git a/files/svncheck b/files/svncheck
--- a/files/svncheck
+++ b/files/svncheck
@@ -3,7 +3,9 @@
 # Managed by Puppet #
 #####################
 # svncheck
-# Usage: Check the status of SVN directory
+# https://github.com/ballestr/puppet-vcscheck
+# Usage: Check the status of VCS directory
+#
 # Author: saqib.haleem
 # Version: 1.0  18.8.2010
 # Update: 1.1 for /etc/svncheck
@@ -19,7 +21,9 @@
 # Update: 1.6 single email for updates, with paths
 # sergio.ballestrero 2015-01-24
 
-MY_NAME=`readlink -f  "$0"`
+# MYNAME=`readlink -f  "$0"` # -f fails on OsX
+MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #"#confusedmcedit
+MYNAME="$MYDIR/$(basename ${BASH_SOURCE[0]})"
 SPREAD=10
 MAIL_CMD="/usr/sbin/sendmail -t"
 USERMAIL=$(mktemp /tmp/vcscheck.XXXXXXXXXX)   # mail text
@@ -36,51 +40,19 @@ fi
 
 if [ "$1" = "-create" ]; then
    DO_CREATE=true
+   DO_EXITCODE=true
    shift
 fi
 
+TYPE="svn"
 if [ $# -eq 0 ]; then
     shopt -s nullglob
-    CONFIGS="/etc/vcscheck/svn_*.rc"
+    CONFIGS="/etc/vcscheck/${TYPE}_*.rc"
 else
     CONFIGS="$@"
 fi
 
-function svn_checkstatus() {
-    CHECK_STATUS=`svn status -u 2>&1 | sed -e '/^Status/ d'` 2>/dev/null
-    R=${PIPESTATUS[0]}
-    if [ "$CHECK_STATUS" == "" ]; then
-        echo "## $CONF: $VCS_DIR status -u ok" >> $USERMAIL
-    elif [[ "$CHECK_STATUS" =~ "Network connection" ]]; then
-        echo -e "## $CONF: network connection failure (s=$CHECK_STATUS):" >> $USERMAIL
-        svn info | grep "^Repository Root:" | sed -e 's/^/-- /' >> $USERMAIL
-        FAIL=1
-    else
-        echo -e "## $CONF: $VCS_DIR is not in sync (r=$R):" >> $USERMAIL
-        svn status -u 2>&1 | sed -e 's/^/-- /' >> $USERMAIL
-        FAIL=1
-    fi
-}
-
-function svn_update() {
-    res=$(svn update | grep -v "At revision")
-    if [ "$res" ]; then
-        echo "## $CONF: updated $VCS_DIR from $VCSSRC"
-        echo "$res"
-    fi
-}
-
-function svn_create() {
-    echo "## $CONF: checkout $SOURCE $VCS_DIR"
-    svn checkout $SOURCE $VCS_DIR
-}
-
-function svn_checkdir() {
-    if [ ! -d $VCS_DIR/.svn ];  then
-        echo "## $CONF: $VCS_DIR is not an SVN working directory." >> $USERMAIL
-        return 1
-    fi
-}
+source $MYDIR/vcslib.sh || source /usr/local/bin/vcslib.sh || exit 1
 
 FAILS=0
 for F in $CONFIGS; do
@@ -98,28 +70,27 @@ for F in $CONFIGS; do
             continue
         fi
 
-        if ! [ -e "$VCS_DIR" -a -e "$VCS_DIR/.svn" ]; then
+        if ! vcs_isvcsdir; then
             if [ -n "$DO_CREATE" -a -n "$SOURCE" ]; then
                 ## if not empty, move aside
                 [ "ls -A $VCS_DIR" ] && mv $VCS_DIR $VCS_DIR.pre_vcscheck
-                svn_create
+                vcs_create
             fi
         fi
-        # must cd to the path, else svn status fails if it is a link
+
+        # must cd to the path, else git status fails, svn status fails if it is a link
         if ! cd $VCS_DIR/ 2>/dev/null ;  then
             echo "## $CONF: $VCS_DIR is not accessible." >> $USERMAIL
             FAIL=1
             continue
         fi
 
-        if ! svn_checkdir;  then
+        if ! vcs_checkdir; then
             FAIL=1
             continue
         fi
 
-        #VCSSRC=$(cd $VCS_DIR; svn info)
-        VCSSRC=$(cd $VCS_DIR; svn info | grep '^URL:' | cut -d' ' -f2)
-        # OLD? VCSSRC=$(head .svn/entries | egrep "^svn.*:" | head -1)
+        vcs_getsrc
 
         if [ -n "$SOURCE" ];  then
             if [ "$VCSSRC" != "$SOURCE" ]; then
@@ -131,22 +102,23 @@ for F in $CONFIGS; do
 
         # let's not hammer the server if running from batch...
         [[ -t 0 || -p /dev/stdin || -n "$SSH_CONNECTION" ]] || sleep $[RANDOM%SPREAD]
-        if [ "$AUTOUPDATE" = "true" -a -n "$DO_UPDATE" ]; then
+        if [ "$AUTOUPDATE" == "true" -a -n "$DO_UPDATE" ]; then
             ## Check if running interactive, else send output to email
-            if [ -t 0 ]; then 
-                svn_update
+            if [[ -t 0 || -n "$SSH_CONNECTION" ]]; then 
+                vcs_update
             else
-                svn_update >> $UPDATEMAIL
+                vcs_update >> $UPDATEMAIL
             fi
         fi
-        svn_checkstatus
+        vcs_checkstatus
     done
 
     ## Notifications
     if [ $FAIL -ne 0 ]; then
         vcsnotify $CONF $USERMAIL
-        if [ -t 0 ] ; then
+        if [[ -t 0 || -n "$SSH_CONNECTION" ]] ; then
             cat $USERMAIL
+            echo ""
         else
             if [ -z "$PUPSRV" ]; then 
                 ## send mail if no report server defined
@@ -165,12 +137,12 @@ if [ -s $UPDATEMAIL ] ; then
 {
     cat $UPDATEMAIL 
     echo "---"
-    echo "Mail sent by $MY_NAME $CONFIGS running on $(hostname)"
-}| mail -s "[SVNCHECK] updates on $(hostname -s)"  $MAILTO
+    echo "Mail sent by $MYNAME $CONFIGS running on $(hostname)"
+}| mail -s "[VCSCHECK] updates on $(hostname -s)"  $MAILTO
 fi
 
 rm $USERMAIL $UPDATEMAIL
 
-## exit code, especially for puppet
-[ $FAILS -ne 0 ] && exit 1
+## exit code, especially for puppet -create
+[ -n "$DO_EXITCODE" -a $FAILS -ne 0 ] && exit 1
 exit 0
